### ISSUE TITLE
post the reports from remote to jenkins local

### ISSUE THREAD

**Issue by wushuzh** [jenkinsci/webhook-step-plugin#11]
Hello,

After remote testing finished, I'd like to collect the generated test reports files from remote system back to jenkins. Then ask jenkins to render the results files using other plugins.

So is it possible for end-user to post the file archives files at remotes server using curl, for example, and then somehow the webhook-step plugin could receive them and save on my jenkins job workspace ?

Best regards,
wushuzh

**Comment by slide** [comment]
You can post any data that you want as the request stream and that data will be available from the step. You may need to post all of the files as a string for it to work correctly.
