### ISSUE TITLE
Add parameter to registerWebhook

### ISSUE THREAD

**Issue by dhagener** [jenkinsci/webhook-step-plugin#3]
The current implementation adds a UUID to the webhook path which is suitable for a simple use case as outlined in the README.

Im my company we have the use case of remote triggering Jenkins pipeline jobs from Atlassian's JIRA. As it is possible to start a new pipeline build from JIRA using the [JIRA Trigger plugin](https://github.com/jenkinsci/jira-trigger-plugin), there has been no way to resume a halted build by actions in JIRA.

**Comment by dhagener** [comment]
[0001-https-github.com-jenkinsci-webhook-step-plugin-issue.patch.zip](https://github.com/jenkinsci/webhook-step-plugin/files/1426763/0001-https-github.com-jenkinsci-webhook-step-plugin-issue.patch.zip)
Attached you will find a patch containing the desired changes.

Please feel free to give me any feedback.

**Comment by cpitman** [comment]
There are several issues this isn't addressing in a general way that need to be addressed before merging:

1. How are multiple simultaneous executions of this step handled? Do they all trigger? The oldest one? What if they are called from different branches/jobs?
2. This change reduces the security inherent in using the UUID. How can we ensure that only authorized systems are posting to this url?

Even in this use case, it seems more robust to post a unique webhook to JIRA via its REST API and then calling it on completion.

**Comment by slide** [comment]
A version of this feature has been merged in.
